### PR TITLE
Added date of posting to listings

### PR DESCRIPTION
**Pull request by Danielpark1239**
- Added date of posting to every page that had an expiration date
- Adjusted posted_date and expiration icons
- Added labels for clarity

### CODE REVIEW

**Review by shannon-heh — COMMENTED** [review]
@Danielpark1239 love the change!! it's a great idea to use hourglass start and end to distinguish posted and expiration times.

before i approve your request, can you include screenshots of your changes? just a couple examples would be sufficient.

**Review by nicholaspad — COMMENTED** [review]
looks good to me! same feedback as @shannon-heh - please add screenshots to your PR summary!

**Comment by Danielpark1239** [comment]
Here are some screenshots of the change:
Screen Shot 2022-12-05 at 12 44 30 PM
Screen Shot 2022-12-05 at 12 44 42 PM
Screen Shot 2022-12-05 at 12 44 58 PM

The items and item_requests page use javascript fetching to query the items, so I formatted the posting date to YYYY-MM-DD to match the expiration date. The rest of the pages use Jinja templating, and by default the posting date also includes the time; I left it in because I think it’s nice to have that info.

Ideally, I’d like the item and item_requests page to also include the time of posting and for all pages to also include time of expiration. The first should be easy to implement but I’d need more information about what time expired items are deleted to implement the latter. Could someone provide me more information about the specific time expired items are set to be deleted? I'd like to make another PR to include times for all posted dates and expiration dates.

**Comment by nicholaspad** [comment]
@Danielpark1239 thanks for the screenshots and explanations! I think it's a great idea adding time.

@shannon-heh recently pushed a daily script that deletes expired listings, and it runs every morning at 4am ET. However, items that are set to expire on a given day may actually be deleted the next day, if the time of posting was after ~4am ET. Therefore I think it's best to leave the expiration date without a specific time, since it's not consistent across listings.

For date of posting I think you can go ahead and add the specific time in another PR like you said!

Overall LGTM, nice work

**Review by nicholaspad — APPROVED** [review]

**Pull request merged**
